# Generated by Django 4.2.5 on 2023-12-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_hargapaket_pesanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hargapaket',
            name='perbulan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
