# Generated by Django 4.2.5 on 2023-12-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_pesanan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
