# Generated by Django 4.2.5 on 2023-10-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
